trigger:
  branches:
    include:
      - dev
      - staging
      - main

pool:
  name: SandBoxAgent

variables:
  - group: DevSettings  # Reads secrets from Key Vault via Variable Group

stages:
- stage: Dev
  displayName: "Deploy to Dev"
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
    - job: DeployDev
      steps:
        - script: echo "Environment Dev"
        - script: echo "DB Connection $(dbConnectionString)"
        - script: echo "API Key $(apiKey)"
