trigger:
  branches:
    include:
      - dev
      - staging
      - main

pool:
  name: SandBoxAgent

# Use the variable group that links to Azure Key Vault
variables:
  - group: SandBox-kv-VariableGroup

stages:
- stage: Dev
  displayName: "Deploy to Dev"
  condition: eq(variables['Build.SourceBranchName'], 'dev')
  jobs:
    - job: DeployDev
      steps:
        - script: echo "Deploying to Dev environment..."
          displayName: "Deployment step"

- stage: Staging
  displayName: "Deploy to Staging"
  condition: eq(variables['Build.SourceBranchName'], 'staging')
  jobs:
    - job: DeployStaging
      steps:
        - script: echo "Deploying to Staging environment..."
          displayName: "Deployment step"

- stage: Prod
  displayName: "Deploy to Production"
  condition: eq(variables['Build.SourceBranchName'], 'main')
  jobs:
    - job: DeployProd
      steps:
        - script: echo "Deploying to Production environment..."
          displayName: "Deployment step"
